-- MySQL Script generated by MySQL Workbench
-- sáb 03 feb 2018 18:52:10 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categories` (
  `id_categories` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `uuid` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_categories`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rating` (
  `id_rating` INT NOT NULL AUTO_INCREMENT,
  `score` INT NULL,
  `uuid` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_rating`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`feeds`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`feeds` (
  `id_feeds` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `source` VARCHAR(3000) NOT NULL,
  `categories_id_categories` INT NOT NULL,
  `uuid` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_feeds`, `categories_id_categories`),
  INDEX `fk_feeds_categories1_idx` (`categories_id_categories` ASC),
  CONSTRAINT `fk_feeds_categories1`
    FOREIGN KEY (`categories_id_categories`)
    REFERENCES `mydb`.`categories` (`id_categories`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`news` (
  `id_news` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `description` MEDIUMTEXT NOT NULL,
  `link` VARCHAR(3000) NOT NULL,
  `pubdate` DATETIME NOT NULL,
  `feeds_id_feeds` INT NOT NULL,
  `rating_id_rating` INT NOT NULL,
  `uuid` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_news`, `feeds_id_feeds`, `rating_id_rating`),
  INDEX `fk_news_feeds1_idx` (`feeds_id_feeds` ASC),
  INDEX `fk_news_rating1_idx` (`rating_id_rating` ASC),
  CONSTRAINT `fk_news_feeds1`
    FOREIGN KEY (`feeds_id_feeds`)
    REFERENCES `mydb`.`feeds` (`id_feeds`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_news_rating1`
    FOREIGN KEY (`rating_id_rating`)
    REFERENCES `mydb`.`rating` (`id_rating`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`static_pages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`static_pages` (
  `id_static_page` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `content` LONGTEXT NOT NULL,
  `uuid` VARCHAR(45) NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contact_messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contact_messages` (
  `idcontact_messages` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `message` LONGTEXT NULL,
  `uuid` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcontact_messages`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`likes` (
  `idlikes` INT NOT NULL AUTO_INCREMENT,
  `user` VARCHAR(45) NOT NULL,
  `news_id_news` INT NOT NULL,
  `news_feeds_id_feeds` INT NOT NULL,
  `news_rating_id_rating` INT NOT NULL,
  `uuid` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idlikes`, `news_id_news`, `news_feeds_id_feeds`, `news_rating_id_rating`),
  INDEX `fk_likes_news1_idx` (`news_id_news` ASC, `news_feeds_id_feeds` ASC, `news_rating_id_rating` ASC),
  CONSTRAINT `fk_likes_news1`
    FOREIGN KEY (`news_id_news` , `news_feeds_id_feeds` , `news_rating_id_rating`)
    REFERENCES `mydb`.`news` (`id_news` , `feeds_id_feeds` , `rating_id_rating`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`shares`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`shares` (
  `idshares` INT NOT NULL AUTO_INCREMENT,
  `user` VARCHAR(45) NOT NULL,
  `news_id_news` INT NOT NULL,
  `news_feeds_id_feeds` INT NOT NULL,
  `news_rating_id_rating` INT NOT NULL,
  `uuid` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idshares`, `news_id_news`, `news_feeds_id_feeds`, `news_rating_id_rating`),
  INDEX `fk_likes_news1_idx` (`news_id_news` ASC, `news_feeds_id_feeds` ASC, `news_rating_id_rating` ASC),
  CONSTRAINT `fk_likes_news10`
    FOREIGN KEY (`news_id_news` , `news_feeds_id_feeds` , `news_rating_id_rating`)
    REFERENCES `mydb`.`news` (`id_news` , `feeds_id_feeds` , `rating_id_rating`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `idusers` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `uuid` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idusers`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
